### ISSUE TITLE
"/home/js/main.js" is missing?

### ISSUE THREAD

**Issue by noonenonamenobody** [sunyan1998/Online-course-website#2]
[前台首页模板](https://github.com/sunnyat/Online-course-website/blob/main/views/home/home.art) 和[search模板](https://github.com/sunnyat/Online-course-website/blob/main/views/home/search.art)里都有引用这个main.js,
 <script src="/home/js/main.js"></script>
我没有找到这个文件，前台首页“新课程”的数据渲染是空白。

**Comment by SergeantMahdi** [comment]
I searched through your files, there isn't such a file is named "main.js", are you sure you haven't saved the file in another name?

**Comment by noonenonamenobody** [comment]
Actually, it doesn't bother so far. Maybe main.js is not needed anyway.

**Comment by noonenonamenobody** [comment]
需要：

1. 以管理员身份登录后台
2. 上传课程
3. 返回前台首页（就能看到课程列表了
